### ISSUE TITLE
Echidna has a dapptool compatibility mode that you can try

### ISSUE THREAD

**Issue by gustavo-grieco** [patrickd-/solidity-fuzzing-boilerplate#1]
Hey, this looks like an awesome project. We will love to see more tool integrating echidna. Btw, we have a dapptool/foundry compatibility mode: https://github.com/crytic/building-secure-contracts/edit/dev-internal-asserts/program-analysis/echidna/testing-modes.md#dapptest

This mode allows to skip a test if the revert reason is `"FOUNDRY::ASSUME"`. Perhaps that can help to simplify your setup.

**Comment by patrickd-** [comment]
Hey, thanks! Yeah, I already had a look at that, but it doesn't make much of a difference for simplification in my eyes..

```solidity
// For skipping invalid fuzzing input.
function assuming(bool condition) {
    // Foundry uses assume cheatcode which is not available in Echidna.
    if (block.gaslimit > 0) { // Echidna's gaslimit is 0.
        CheatCodes(HEVM_ADDRESS).assume(condition);
    }
    // For Echidna in assertion testMode use require() instead.
    require(condition);
}
```

what would help would be some way to avoid the dirty hack above.. or wait, can I replace the cheatcode call with that revert reason too? .. need to give it a try..

**Comment by gustavo-grieco** [comment]
> can I replace the cheatcode call with that revert reason too? .. need to give it a try..

Yes, but only in `dapptest` mode.

**Comment by patrickd-** [comment]
Nope, doesn't work with foundry

```
function assuming(bool condition) pure {
    require(condition, "FOUNDRY::ASSUME");
}
```

```
ubuntu@eth:~/projects/solidity-fuzzing-boilerplate$ forge test --match test_BytesLib_slice
[⠊] Compiling...
No files changed, compilation skipped

Running 1 test for src/test/example/BytesLib.sol:Test
[FAIL. Reason: FOUNDRY::ASSUME. Counterexample: calldata=0x34cec2fd0000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000, args=[0x, 0, 1]] test_BytesLib_slice(bytes,uint256,uint256) (runs: 1, μ: 2645, ~: 2645)
Traces:
  [732] Test::test_BytesLib_slice(0x, 0, 1) 
    └─ ← "FOUNDRY::ASSUME"

Test result: FAILED. 0 passed; 1 failed; finished in 6.41ms

Failed tests:
[FAIL. Reason: FOUNDRY::ASSUME. Counterexample: calldata=0x34cec2fd0000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000, args=[0x, 0, 1]] test_BytesLib_slice(bytes,uint256,uint256) (runs: 1, μ: 2645, ~: 2645)

Encountered a total of 1 failing tests, 0 tests succeeded
```

**Comment by patrickd-** [comment]
For me the dapptest mode isn't really helpful since I can just use normal require()s in assert mode to get the same effect. What would actually be helpful is that Echidna doesn't get stuck when a `CheatCodes(HEVM_ADDRESS).assume(condition);` call is made

**Comment by patrickd-** [comment]
Like this:

```
function assuming(bool condition) {
    CheatCodes(HEVM_ADDRESS).assume(condition);
}
```

```
                                                                                                                                                        
                ┌─────────────────────────────────────────────────────Echidna 2.0.0────────────────────────────────────────────────────┐                
                │ Tests found: 0                                                                                                       │                
                │ Seed: 0                                                                                                              │                
                │─────────────────────────────────────────────────────────Tests────────────────────────────────────────────────────────│                
                │ Starting up, please wait...                                                                                          │                
                └──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘             
```

**Comment by patrickd-** [comment]
I've changed it to use dapptest mode here: https://github.com/patrickd-/solidity-fuzzing-boilerplate/commit/bcf0e4620c9ee8916f9f82153187750ddaff5849

Although it doesn't help me to avoid the mentioned workaround, it does ensure that reverts are handled the same way in both fuzzers, that should avoid some confusion

**Comment by gustavo-grieco** [comment]
Let me investigate this issue..

**Comment by gustavo-grieco** [comment]
> For me the dapptest mode isn't really helpful since I can just use normal require()s in assert mode to get the same effect. What would actually be helpful is that Echidna doesn't get stuck when a `CheatCodes(HEVM_ADDRESS).assume(condition);` call is made

It seems that hevm is aborting the execution when using invalid cheatcodes (assume is not implemented):

> VM failed for unhandled reason, BadCheatCode (Just 1281615202). This shouldn't happen. Please file a ticket with this error message and steps to reproduce!

but Echidna won't properly show that on the screen, unless you use `--format text` so it is a UI issue (and we will fix that!). In any case, if you a better feature parity, we should ask the dapptools team to add a "compatible" `assume` cheatcode.
